services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "debian"
      CPU_CORES: "2"          # kurangi biar stabil di GitHub runner
      RAM_SIZE: "8G"          # github runner cuma punya 7GB RAM total
      DISK_SIZE: "15G"
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
    volumes:
      - ./qemu_storage:/storage
    restart: unless-stopped
    stop_grace_period: 1m
